export const activityDefaults = {
  paddleboarding: {
    tideMin: -2,
    tideMax: 15,
    tideRange: [6, 15],
    temperatureMin: 0,
    temperatureMax: 120,
    temperatureRange: [60, 110],
    windSpeedMin: 0,
    windSpeedMax: 40,
    windSpeedRange: [0, 8],
    skyCoverMin: 0,
    skyCoverMax: 100,
    skyCoverRange: [0, 75],
    precipChanceMin: 0,
    precipChanceMax: 100,
    precipChanceRange: [0, 25],
    requireDaylight: true
  },
  polarplunging: {
    tideMin: -2,
    tideMax: 15,
    tideRange: [7, 12],
    temperatureMin: 0,
    temperatureMax: 120,
    temperatureRange: [10, 80],
    windSpeedMin: 0,
    windSpeedMax: 40,
    windSpeedRange: [0, 10],
    skyCoverMin: 0,
    skyCoverMax: 100,
    skyCoverRange: [0, 100],
    precipChanceMin: 0,
    precipChanceMax: 100,
    precipChanceRange: [0, 25],
    requireDaylight: false
  },
  sailing: {
    tideMin: -2,
    tideMax: 15,
    tideRange: [2, 12],
    temperatureMin: 0,
    temperatureMax: 120,
    temperatureRange: [40, 100],
    windSpeedMin: 0,
    windSpeedMax: 40,
    windSpeedRange: [10, 30],
    skyCoverMin: 0,
    skyCoverMax: 100,
    skyCoverRange: [0, 80],
    precipChanceMin: 0,
    precipChanceMax: 100,
    precipChanceRange: [0, 30],
    requireDaylight: true
  },
  powerboating: {
    tideMin: -2,
    tideMax: 15,
    tideRange: [5, 12],
    temperatureMin: 0,
    temperatureMax: 120,
    temperatureRange: [60, 100],
    windSpeedMin: 0,
    windSpeedMax: 40,
    windSpeedRange: [0, 15],
    skyCoverMin: 0,
    skyCoverMax: 100,
    skyCoverRange: [0, 100],
    precipChanceMin: 0,
    precipChanceMax: 100,
    precipChanceRange: [0, 30],
    requireDaylight: true
  },
  running: {
    tideMin: -2,
    tideMax: 15,
    tideRange: [0, 12],
    temperatureMin: 0,
    temperatureMax: 120,
    temperatureRange: [20, 90],
    windSpeedMin: 0,
    windSpeedMax: 40,
    windSpeedRange: [0, 15],
    skyCoverMin: 0,
    skyCoverMax: 100,
    skyCoverRange: [0, 100],
    precipChanceMin: 0,
    precipChanceMax: 100,
    precipChanceRange: [0, 20],
    requireDaylight: false
  },
  surfing: {
    tideMin: -2,
    tideMax: 15,
    tideRange: [4, 10],
    temperatureMin: 0,
    temperatureMax: 120,
    temperatureRange: [50, 90],
    windSpeedMin: 0,
    windSpeedMax: 40,
    windSpeedRange: [5, 20],
    skyCoverMin: 0,
    skyCoverMax: 100,
    skyCoverRange: [0, 100],
    precipChanceMin: 0,
    precipChanceMax: 100,
    precipChanceRange: [0, 20],
    requireDaylight: true
  }
};
